# Generated by Django 2.1.7 on 2019-09-01 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_file', models.FileField(upload_to='media/site_docs/')),
                ('genre', models.CharField(choices=[('Anthem', 'ANTHEM'), ('Classical', 'CLASSICAL'), ('Highlife', 'HIGHLIFE'), ('Hymn', 'HYMN')], default='Anthem', max_length=30, null=True)),
                ('new_price', models.IntegerField(default='0.00', null=True)),
                ('sample_view', models.ImageField(default='/media/sample_score.jpg', upload_to='sample_sheet')),
                ('lyrics', models.TextField(max_length=1000, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('song_title', models.CharField(max_length=50)),
                ('song_composer', models.CharField(max_length=50, null=True)),
                ('your_email', models.CharField(max_length=50, null=True)),
                ('your_contact', models.CharField(max_length=15)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
