# Generated by Django 2.1.7 on 2019-10-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesting',
            old_name='your_name',
            new_name='your_names',
        ),
    ]
